#!/bin/bash -e
# Test csv2gnuplot script
../csv2gnuplot -i disktable.csv -d table -t "Disk Comparison" -o disks.png
../csv2gnuplot -i iostat.log -d iostat -t "pgbench disk utilization" --disks="sdc" --diskstats="%util" -o iostat-util.png
../csv2gnuplot -i vmstat.log -d vmstat -t "pgbench vmstat" -o vmstat.png
