#!/bin/bash

#Cleaning results from a range of test numbers

source ./config
START=$1
END=$2

pushd "results/${SERVERNAME}"
psql -d results -At -c "SELECT test FROM tests WHERE server='${SERVERNAME}' AND test>=$START AND test<=$END" | xargs rm -rf
psql -d results -At -c "DELETE FROM test_bgwriter WHERE server='${SERVERNAME}' AND test>=$START AND test<=$END"
psql -d results -At -c "DELETE FROM test_stat_database WHERE server='${SERVERNAME}' AND test>=$START AND test<=$END"
psql -d results -At -c "DELETE FROM test_statio WHERE server='${SERVERNAME}' AND test>=$START AND test<=$END"
psql -d results -At -c "DELETE FROM tests WHERE server='${SERVERNAME}' AND test>=$START AND test<=$END"
popd
