#!/bin/bash

source ./config
TEST=$1
if [ -n "$2" ] ; then
	SERVERNAME=$2
fi

echo $SERVERNAME
exit
pushd "results/${SERVERNAME}"
psql -d results -At -c "SELECT test FROM tests WHERE server='${SERVERNAME}' AND test=$TEST" | xargs rm -rf
psql -d results -At -c "DELETE FROM test_bgwriter WHERE server='${SERVERNAME}' AND test=$TEST"
psql -d results -At -c "DELETE FROM test_stat_database WHERE server='${SERVERNAME}' AND test=$TEST"
psql -d results -At -c "DELETE FROM test_statio WHERE server='${SERVERNAME}' AND test=$TEST"
psql -d results -At -c "DELETE FROM tests WHERE server='${SERVERNAME}' AND test=$TEST"
psql -d results -At -c "DELETE FROM test_metrics_data WHERE server='${SERVERNAME}' AND test=$TEST"
psql -d results -At -c "DELETE FROM test_settings WHERE server='${SERVERNAME}' AND test=$TEST"
psql -d results -At -c "DELETE FROM test_statements WHERE server='${SERVERNAME}' AND test=$TEST"
popd
