#!/usr/local/bin/python3

import pandas as pd
import csv
import os

import logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def json_pandas(fn):
        df=pd.read_json(fn)
        logger.debug("pandas loaded from '%s'",fn)
        return df

def csv_in(fn,index_col):
	df = pd.read_csv(fn,index_col=index_col)
	return df
 
def main():
	base="regress/480/"
	io=json_pandas(os.path.join(base,"iostat.json"))
	vm=json_pandas(os.path.join(base,"vmstat.json"))
	me=json_pandas(os.path.join(base,"meminfo.json"))
	tps_stats=csv_in(os.path.join(base,"latency_1s.csv"),'collected')

	t=io.append(vm)
	t=t.append(me)
	t=t.append(tps_stats)

	print(t)

	fn="combined.json"
	t.to_json(fn)
	logger.warning("json saved to '%s'",fn)

if __name__ == '__main__':
    main()
