#!/usr/bin/env python

import sys
import datetime
import string
import time
import dateutil.parser

for l in sys.stdin:
  l=l.strip()
  (ts,key,val)=string.split(l,"\t",2)
  t=dateutil.parser.parse(ts)
  epoch=time.mktime(t.timetuple())
  if key=="Dirty":
    print epoch,val
