#!/bin/bash

#
# summary connects to the Results database and produces a report
# of its contents
#

source ./config
RESULTPSQL="psql -X -h $RESULTHOST -U $RESULTUSER -p $RESULTPORT -d $RESULTDB"
$RESULTPSQL -f reports/report_latest.sql
