#!/bin/bash

. ./config

# Confirm we have a useful pgbench to run
if [ -z $PGBENCHBIN ] || [ ! -x $PGBENCHBIN ]; then
  echo ERROR:  cannot find pgbench binary $PGBENCHBIN , aborting
  exit
fi

TESTPSQL="psql -h $TESTHOST -U $TESTUSER -p $TESTPORT -d $TESTDB"

# See if this database has all the standard pgbench tables in it
PGCOUNT=`$TESTPSQL -A -q -t -c "SELECT count(*)  FROM pg_stat_user_tables WHERE relname IN ('pgbench_history','pgbench_tellers','pgbench_accounts','pgbench_branches')"`
if [ "$PGCOUNT" -eq 4 ] ; then
  TABLEPREFIX="pgbench_"
  PGBENCH_TABLES=1
else
  TABLEPREFIX=""
  PGCOUNT=`$TESTPSQL -A -q -t -c "SELECT count(*)  FROM pg_stat_user_tables WHERE relname IN ('history','tellers','accounts','branches')"`
  if [ "$PGCOUNT" -eq 4 ] ; then
    PGBENCH_TABLES=1
  else
    PGBENCH_TABLES=0
  fi
fi

# Make sure the configured test script actually exists
if [ ! -f "${TESTDIR}/${SCRIPT}.sql" ]; then
  echo "ERROR: cannot find test script ${TESTDIR}/${SCRIPT}.sql, aborting"
  exit
fi

for SCALE in $SCALES; do
  #
  # Have a consistent, clean set of pgbench tables to start 
  # each test run with
  #

  if [ "$SKIPINIT" -ne "1" ]; then
    if [ "$PGBENCH_TABLES" -eq "1" ] ; then
      echo Removing old pgbench tables
      $TESTPSQL -c "drop table ${TABLEPREFIX}accounts; drop table ${TABLEPREFIX}branches; drop table ${TABLEPREFIX}tellers; drop table ${TABLEPREFIX}history;"
    fi
    $TESTPSQL -c "vacuum"
    echo Creating new pgbench tables scale=$SCALE

    if [ -n "$NEWINIT" ] ; then
      cp config config.orig
      echo "SCRIPT=:-i" >> config
      export SCALE && ./benchwarmer 1
      cp config.orig config
    else
     time $PGBENCHBIN -i -s $SCALE -h $TESTHOST -U $TESTUSER -p $TESTPORT $TESTDB
    fi

  fi
  #
  # Run the main test
  #
  for (( t=1; t<=$SETTIMES; t++ )); do
    for c in $SETCLIENTS; do
      if [ -z "$SETRATES" ] && [ -z "$CLIENTRATES" ] ; then
        echo Run set \#$t of $SETTIMES with $c clients scale=$SCALE
        ./benchwarmer $c
      elif [ -z "$CLIENTRATES" ] ; then
        for r in $SETRATES; do
          echo Run set \#$t of $SETTIMES with $c clients scale=$SCALE rate=$r
          ./benchwarmer $c $r
        done
      else
        for l in $CLIENTRATES; do
          r=`expr $c \* $l`
          echo Run set \#$t of $SETTIMES with $c clients @ target=$l scale=$SCALE rate=$r
          ./benchwarmer $c $r $l
        done 
      fi
      echo
    done
  done
done

echo Generating web report
./webreport

echo runset complete
date
