#!/usr/bin/env python

# timed-os-stats
# Copyright 2012 Greg Smith gsmith@gregsmith.com
#
# Runs a command that produces regularly time output and adds time
# stamps for each line when appropriate.  Typical commands it might
# be used for are vmstat and iostat.
#
# On Linux the iostat command produces complicated output for each
# sample, such that a more complicated parser is needed to decode
# everything.  The program presumes that will be handled by a
# downstream tool.  It only tags before the first line in each
# each sample (the one starting with "avg-cpu:") in that
# case.
#

import subprocess
import sys
import datetime

class FlushFile(object):
    """Write-only flushing wrapper for file-type objects."""
    def __init__(self, f):
        self.f = f
    def write(self, x):
        self.f.write(x)
        self.f.flush()

# Replace stdout with an automatically flushing version
sys.stdout = FlushFile(sys.__stdout__)

def capture(cmd,tag_all=True,tag_when=None):
    p = subprocess.Popen(cmd, shell = True,
                         stdout = subprocess.PIPE,
                         stderr = subprocess.STDOUT,
                         )                         

    pid = p.pid

    while True:
        line = p.stdout.readline()
        if line == '' and p.poll() != None:
            break

        if tag_all:
            sys.stdout.write("%s\t" % datetime.datetime.now())
        elif tag_when != None and line.find(tag_when)>=0:
            sys.stdout.write("%s\n" % datetime.datetime.now())

        sys.stdout.write(line)

    retcode = p.returncode

def usage():
    print >> sys.stderr, "Usage:  %s [vmstat | iostat]" % sys.argv[0]
    print >> sys.stderr, "Supported platforms are linux and darwin"
    sys.exit(1)

if __name__=='__main__':
    if len(sys.argv)<2:
        usage()

    cmd=sys.argv[1]

    if sys.platform.startswith('linux'):
        if cmd=='vmstat':
            capture("vmstat 5")
        elif cmd=='iostat':
            capture("iostat -mx 5",False,"avg-cpu:")
        else:
            usage()

    elif sys.platform.startswith('darwin'):
        if cmd=='vmstat':
            capture("vm_stat 5")
        elif cmd=='iostat':
            capture("iostat -d -C -K 5")
        else:
            usage()
    else:
        print >> sys.stderr, 'Unsupported platform', sys.platform
