#!/bin/bash -ex
rm -f iostat.png iostat.json vmstat.png vmstat.json dirtydata.txt iostat.csv meminfo.csv vmstat.csv
../../csv2gnuplot -i vmstat.log -d vmstat -t "pgbench vmstat" -o vmstat
../../csv2gnuplot -i iostat.log -d iostat -t "pgbench disk" --disks="nvme2n1" -o iostat
../../dirty-plot < meminfo.log > dirtydata.txt
psql -d results -f ../../export-latency-metric.sql

psql -d results -c "TRUNCATE TABLE tmp_metric_import;"
psql -d results -c "\copy tmp_metric_import FROM 'latency_metric.csv' WITH CSV HEADER"
psql -d results -c "\copy tmp_metric_import FROM 'vmstat.csv' WITH CSV HEADER"
psql -d results -c "\copy tmp_metric_import FROM 'iostat.csv' WITH CSV HEADER"
psql -d results -c "\copy tmp_metric_import FROM 'meminfo.csv' WITH CSV HEADER"

psql -d results -c "TRUNCATE TABLE test_metrics_data;"
psql -d results -c "INSERT INTO test_metrics_data SELECT collected,value,metric,480,'fragile'  FROM tmp_metric_import;"


