#!/bin/bash -ex
# basic-check workload set for pgbench automation

./pgsysinfo > params
. ./params

./newset "SELECT"
wl/select-grid
./runset

./newset "Multiplied read"
wl/multis

# TODO Only need subset of SCALES given current pgbench INSERT test
./newset "INSERT"

echo "SETCLIENTS=\"$SETCLIENTS\""  > params
echo "SCALES=\"$SCALES\""  >> params
# Setting SCRIPT and RUNTIME here temporarily, until wl/insert is sorted out.
echo "SCRIPT=insert"  >> params
echo "RUNTIME=60"  >> params
#wl/insert
#./runset
echo "INSERT not finished yet"
echo Finished basic-check workload
