#!/bin/bash -ex

# multis workload for pgbench automation
#
# This approach expects a test database at least 4X RAM on the server,
# while up to 8X also works.
#
# The script presumes you've already created a test database.
# It's designed to run after the select grid workload creates one.
# Workloads may find it easier to modify this script to initialize
# the database at its start instead.  

MULTI="0 1 2 3 4 5 8 10 20 40 50 60 70 80 100 150 200 250 500 1000"
MULTI_CLIENTS="16 32"

SCRIPT="select-pages"
SETTIMES=1
RUNTIME=60
echo "SCRIPT=$SCRIPT "  >> params
echo "SETTIMES=$SETTIMES "  >> params
echo "RUNTIME=$RUNTIME "  >> params
for m in $MULTI ; do
  echo MULTI=$m
  echo "MULTI=$m"  >> params
  for c in $MULTI_CLIENTS ; do
    ./benchwarmer $c
  done
done
echo Finished multis multiplied read workload
