#!/bin/bash -ex
# osm2pgsql sample workload for pgbench automation.

. ./config

# TODO Validate cloud URI connections work.  Presumably resetting TESTDB here won't do anything to them.

./pgsysinfo > params
. ./params

if [ -z "${OSMNODECACHE}" ] ; then
  OSMNODECACHE=0
fi

cat << EOF >> params
SETCLIENTS="2"
SETTIMES=1
SCALES="${OSMNODECACHE}"
SCALE="${OSMNODECACHE}"
PGBENCHBIN=$BASEDIR/util/osm-importer
SCRIPT="osm2pgsql-1.6"
TESTDB="gis"
SKIPINIT=1
MULTI=5
EOF

# TODO Correct connection string
dropdb gis
createdb gis
psql -d gis -c "create extension postgis"
psql -d gis -c "create extension hstore"
psql -d gis -c "create extension pg_stat_statements"
psql -d gis -c "create extension pg_buffercache"

./newset "OSM"
./runset
