#!/bin/bash -ex
# select-grid workload for pgbench automation

SCRIPT="select"
SETTIMES=3
RUNTIME=60

echo "SCRIPT=$SCRIPT "  >> params
echo "SETTIMES=$SETTIMES "  >> params
echo "RUNTIME=$RUNTIME "  >> params
./pgsysinfo >> params

./runset

echo Finished select-grid workload
