#!/bin/bash
# Linux drop OS caching as user like postgres, probably with sudo.
# Suggested install directory is /usr/local/bin
#
# For Debian/Ubuntu Linux installs, supports two optional parameters:
# version of PG and cluster name to restart as part of cache dropping.
# Sample:
#
#   /usr/local/bin/drop_caches 17 main
#
# Starting from a checkout of pgbench-tools into the postgres user's home directory, you
# likely need to run sudo as another user to install this, then add a sudo rule to allow
# the postgres user to run it.  This idiom works here:
#
#    cp util/drop_caches /tmp
#    logout
#    sudo cp /tmp/drop_caches /usr/local/bin/
#    sudo sh -c "echo \"postgres ALL = (ALL) NOPASSWD: /usr/local/bin/drop_caches\" >> /etc/sudoers.d/postgres"
#

if [[ $(id -u) -ne 0 ]] ; then echo "Cache dropping must run as root" ; exit 1 ; fi

# TODO Wrap the cluster parameters better to reduce sudo exploit potential.
if [ -n "$2" ] ; then
  svctl $1 $2 restart:wq
fi

echo -n "Dropping "
grep ^Cached: /proc/meminfo
sync
echo 3 > /proc/sys/vm/drop_caches
