#!/bin/bash
# Drop and recreate test database with extensions including PostGIS
# Missing the URI handling needed to recreate Crunchy Bridge instances.
. ./config
. ./params
TESTPSQL="psql -h $TESTHOST -U $TESTUSER -p $TESTPORT -d $TESTDB"
TESTCONN="-h $TESTHOST -U $TESTUSER -p $TESTPORT"
# TODO psql handles TESTDB being a URI; drop/create needs another approach.
set -x
dropdb $TESTCONN $TESTDB
set -e
createdb $TESTCONN $TESTDB
$TESTPSQL -c "create extension pg_stat_statements"
$TESTPSQL -c "create extension pg_buffercache"
$TESTPSQL -c "create extension postgis"
$TESTPSQL -c "create extension hstore"
