#!/bin/bash -e
. ./config
. ./params
TESTPSQL="psql -h $TESTHOST -U $TESTUSER -p $TESTPORT -d $TESTDB"
df -h | egrep -v "/sys/fs/cgroup|/sys/firmware/|/boot/efi|^/dev/loop|^tmpfs|^efivarfs|^udev|^devfs|/System/Volumes/"
echo
$TESTPSQL -c "SELECT pg_size_pretty(pg_database_size(current_database())) AS db_size,pg_size_pretty(sum(size)) AS wal_used FROM pg_ls_waldir()"
echo
tail nohup.out
